### ISSUE TITLE
Call to undefined function WP_CLI\Utils\wp_get_table_names()

### ISSUE THREAD

**Issue by robertmathews** [runcommand/db-ack#18]
I'm using db-ack with wp-cli 1.5.0. When I run it, I get this error (which did not happen with earlier versions of wp-cli):

PHP Fatal error:  Uncaught Error: Call to undefined function WP_CLI\Utils\wp_get_table_names() in /usr/local/etc/wp-cli/packages/vendor/runcommand/db-ack/command.php:75

Here's the full output with --debug:

```$ wp db ack test --debug
Debug (bootstrap): Loading packages from: /usr/local/etc/wp-cli/packages/vendor/autoload.php (0.012s)
Debug (commandfactory): No doc comment for profile. (0.019s)
Debug (bootstrap): Using global config from WP_CLI_CONFIG_PATH env var: /usr/local/etc/wp-cli/config.yml (0.082s)
Debug (bootstrap): No project config found (0.082s)
Debug (bootstrap): argv: /usr/local/bin/wp-cli db ack test --debug (0.082s)
Debug (bootstrap): ABSPATH defined: /var/www/html/ne/newwaverevisited.com/subdir/ (0.082s)
Debug (bootstrap): Begin WordPress load (0.083s)
Debug (bootstrap): wp-config.php path: /var/www/html/ne/newwaverevisited.com/subdir/wp-config.php (0.083s)
Debug (bootstrap): Running command: db ack (0.084s)
PHP Fatal error:  Uncaught Error: Call to undefined function WP_CLI\Utils\wp_get_table_names() in /usr/local/etc/wp-cli/packages/vendor/runcommand/db-ack/command.php:75
Stack trace:
#0 [internal function]: Run_DB_Ack_Command->__invoke(Array, Array)
#1 phar:///usr/local/bin/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(89): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(425): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp-cli/php/WP_CLI/Runner.php(353): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp-cli/php/WP_CLI/Runner.php(376): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp-cli/php/WP_CLI/Runner.php(83): WP_CLI\Runner->_run_command_and_exit()
#7 phar:///usr/local/bin/wp-cli/php/WP_CLI/Runner.php(1149): WP_CLI\Runner->do_early_invoke('after_wp_config...')
#8 phar:///usr/local/bin/wp in /usr/local/etc/wp-cli/packages/vendor/runcommand/db-ack/command.php on line 75
```

Looking at the [internal API docs](https://make.wordpress.org/cli/handbook/internal-api/), it appears that wp_get_table_names() is not a documented API anymore.

Looking at the wp-cli code, wp_get_table_names() is a defined function, but it's in "utils-wp.php", not the "utils.php" file that contains the documented API functions.

**Comment by danielbachhuber** [comment]
You should use `wp db search` instead: https://developer.wordpress.org/cli/commands/db/search/

**Comment by robertmathews** [comment]
Thanks for the reply! As a suggestion, maybe the README.md could be updated to say that wp db ack should no longer be used.

**Comment by danielbachhuber** [comment]
Good point, updated 20151e144736f6dbbc52d274b81b6c29d416d259
